import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  systemConfiguration: defineTable({
    key: v.literal("global"),
    systemName: v.string(),
    registrationFeeKes: v.number(),
    maxActiveMembersPerGroup: v.number(),
    cashLoanSavingsPercent: v.number(),
    cashLoanRepaymentDays: v.number(),
    cashLoanFinePercent: v.number(),
    requireMfaForPrivileged: v.boolean(),
    updatedAt: v.number(),
  }),
  users: defineTable({
    email: v.string(),
    passwordHash: v.string(),
    emailVerified: v.boolean(),
    status: v.union(v.literal("INVITED"), v.literal("ACTIVE"), v.literal("SUSPENDED"), v.literal("LOCKED"), v.literal("DEACTIVATED")),
    forcePasswordChange: v.boolean(),
    loginFailedCount: v.number(),
    lockedUntil: v.optional(v.number()),
    lastLoginAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
    deletedAt: v.optional(v.number()),
  }).index("by_email", ["email"]),
  sessions: defineTable({
    token: v.string(),
    userId: v.id("users"),
    status: v.union(v.literal("ACTIVE"), v.literal("REVOKED"), v.literal("EXPIRED")),
    mfaCompletedAt: v.optional(v.number()),
    expiresAt: v.number(),
    lastSeenAt: v.number(),
    ipHash: v.optional(v.string()),
    userAgentHash: v.optional(v.string()),
    createdAt: v.number(),
    revokedAt: v.optional(v.number()),
    revocationReason: v.optional(v.string()),
  }).index("by_token", ["token"]),
  members: defineTable({
    userId: v.id("users"),
    email: v.optional(v.string()),
    fullName: v.string(),
    phoneE164: v.optional(v.string()),
    memberNumber: v.string(),
    registrationDate: v.number(),
    profilePhotoFileId: v.optional(v.string()),
    status: v.union(v.literal("INVITED"), v.literal("ACTIVE"), v.literal("SUSPENDED")),
    role: v.union(v.literal("OWNER"), v.literal("ADMIN"), v.literal("MEMBER")),
    createdAt: v.number(),
  }).index("by_user_id", ["userId"]),
  invitations: defineTable({
    email: v.string(),
    role: v.union(v.literal("OWNER"), v.literal("ADMIN"), v.literal("MEMBER")),
    status: v.union(v.literal("PENDING"), v.literal("ACCEPTED"), v.literal("REVOKED"), v.literal("EXPIRED")),
    expiresAt: v.number(),
    consumedAt: v.optional(v.number()),
    createdById: v.id("users"),
    createdAt: v.number(),
  }).index("by_email_status", ["email", "status"]),
  groups: defineTable({
    name: v.string(),
    status: v.union(v.literal("DRAFT"), v.literal("READY"), v.literal("ACTIVE"), v.literal("SUSPENDED"), v.literal("ARCHIVED")),
    savingsPolicyJson: v.string(),
    constitutionVersion: v.number(),
    createdById: v.id("users"),
    createdAt: v.number(),
    updatedAt: v.number(),
    suspendedAt: v.optional(v.number()),
  }),
  memberships: defineTable({
    groupId: v.id("groups"),
    memberId: v.id("members"),
    status: v.union(v.literal("ACTIVE"), v.literal("LEFT"), v.literal("SUSPENDED")),
    joinedAt: v.number(),
    leftAt: v.optional(v.number()),
    createdById: v.optional(v.id("users")),
  }).index("by_member_group", ["memberId", "groupId"]),
  registrationFees: defineTable({
    groupId: v.id("groups"),
    memberId: v.id("members"),
    amountKes: v.number(),
    status: v.union(v.literal("PENDING"), v.literal("PAID"), v.literal("WAIVED")),
    paidAt: v.optional(v.number()),
    recordedById: v.optional(v.id("users")),
    createdAt: v.number(),
  }).index("by_group_member", ["groupId", "memberId"]),
  savingsAccounts: defineTable({
    groupId: v.id("groups"),
    memberId: v.id("members"),
    openedAt: v.number(),
    closedAt: v.optional(v.number()),
  }).index("by_group_member", ["groupId", "memberId"]),
  savingsEntries: defineTable({
    savingsAccountId: v.id("savingsAccounts"),
    groupId: v.id("groups"),
    memberId: v.id("members"),
    contributionWeek: v.number(),
    amountKes: v.number(),
    reference: v.string(),
    status: v.union(v.literal("POSTED"), v.literal("REVERSED")),
    reversalOfId: v.optional(v.id("savingsEntries")),
    recordedById: v.optional(v.id("users")),
    createdAt: v.number(),
  }).index("by_member_group", ["memberId", "groupId"]),
  cashLoans: defineTable({
    groupId: v.id("groups"),
    memberId: v.id("members"),
    principalKes: v.number(),
    outstandingKes: v.number(),
    issueDate: v.optional(v.number()),
    dueDate: v.optional(v.number()),
    status: v.union(v.literal("PENDING"), v.literal("VERIFIED"), v.literal("ACTIVE"), v.literal("PAID"), v.literal("OVERDUE"), v.literal("FINE_APPLIED"), v.literal("SUSPENDED"), v.literal("CANCELLED")),
    verificationStatus: v.string(),
    verifiedById: v.optional(v.id("users")),
    verifiedAt: v.optional(v.number()),
    clearedAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_group_status", ["groupId", "status"]),
  cashLoanPayments: defineTable({
    cashLoanId: v.id("cashLoans"),
    amountKes: v.number(),
    paymentDate: v.number(),
    reference: v.string(),
    verifiedById: v.optional(v.id("users")),
    createdAt: v.number(),
  }).index("by_cash_loan", ["cashLoanId"]),
  loanFines: defineTable({
    cashLoanId: v.id("cashLoans"),
    amountKes: v.number(),
    ruleVersion: v.number(),
    status: v.union(v.literal("PENDING"), v.literal("PAID"), v.literal("WAIVED")),
    appliedAt: v.number(),
    clearedAt: v.optional(v.number()),
  }).index("by_cash_loan", ["cashLoanId"]),
  items: defineTable({
    groupId: v.id("groups"),
    name: v.string(),
    description: v.optional(v.string()),
    priceKes: v.number(),
    availableFrom: v.number(),
    availableUntil: v.number(),
    status: v.union(v.literal("DRAFT"), v.literal("ACTIVE"), v.literal("INACTIVE"), v.literal("ARCHIVED")),
    createdById: v.id("users"),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_group_status", ["groupId", "status"]),
  itemLoans: defineTable({
    groupId: v.id("groups"),
    itemId: v.id("items"),
    memberId: v.id("members"),
    priceKes: v.number(),
    outstandingKes: v.number(),
    status: v.union(v.literal("SELECTED"), v.literal("PENDING"), v.literal("CLEARED"), v.literal("OUTSTANDING"), v.literal("CANCELLED")),
    selectedAt: v.number(),
    clearedAt: v.optional(v.number()),
    verifierId: v.optional(v.id("users")),
  }).index("by_group_status", ["groupId", "status"]),
  itemLoanPayments: defineTable({
    itemLoanId: v.id("itemLoans"),
    amountKes: v.number(),
    paymentDate: v.number(),
    reference: v.string(),
    verifiedById: v.optional(v.id("users")),
    createdAt: v.number(),
  }).index("by_item_loan", ["itemLoanId"]),
  financialLedgerEntries: defineTable({
    groupId: v.id("groups"),
    memberId: v.optional(v.id("members")),
    category: v.union(v.literal("REGISTRATION_FEE"), v.literal("SAVINGS"), v.literal("CASH_LOAN"), v.literal("CASH_LOAN_PAYMENT"), v.literal("LOAN_FINE"), v.literal("ITEM_LOAN"), v.literal("ITEM_LOAN_PAYMENT"), v.literal("ADJUSTMENT")),
    direction: v.union(v.literal("DEBIT"), v.literal("CREDIT")),
    amountKes: v.number(),
    referenceType: v.string(),
    referenceId: v.id("_any"),
    idempotencyKey: v.string(),
    reversalOfId: v.optional(v.id("financialLedgerEntries")),
    createdById: v.optional(v.id("users")),
    createdAt: v.number(),
  }).index("by_group_category", ["groupId", "category"]),
  fileAssets: defineTable({
    purpose: v.union(v.literal("PROFILE_PHOTO"), v.literal("AGREEMENT"), v.literal("REPORT"), v.literal("EXPORT"), v.literal("OTHER")),
    storageKey: v.string(),
    contentHash: v.string(),
    contentType: v.string(),
    byteSize: v.number(),
    width: v.optional(v.number()),
    height: v.optional(v.number()),
    createdById: v.optional(v.id("users")),
    createdAt: v.number(),
    deletedAt: v.optional(v.number()),
  }).index("by_purpose_created", ["purpose", "createdAt"]),
  memberAgreements: defineTable({
    groupId: v.id("groups"),
    memberId: v.id("members"),
    fileAssetId: v.id("fileAssets"),
    version: v.number(),
    contentHash: v.string(),
    status: v.union(v.literal("DRAFT"), v.literal("ISSUED"), v.literal("SIGNED"), v.literal("SUPERSEDED"), v.literal("VOID")),
    issuedAt: v.optional(v.number()),
    signedAt: v.optional(v.number()),
    supersedesId: v.optional(v.id("memberAgreements")),
    createdAt: v.number(),
  }).index("by_member_version", ["memberId", "version"]),
  agreementSignatures: defineTable({
    memberAgreementId: v.id("memberAgreements"),
    signerUserId: v.id("users"),
    signerRoleSnapshot: v.string(),
    signedAt: v.number(),
    signatureMethod: v.string(),
    signatureEvidenceHash: v.string(),
  }).index("by_agreement_signed", ["memberAgreementId", "signedAt"]),
  chatConversations: defineTable({
    groupId: v.optional(v.id("groups")),
    type: v.union(v.literal("MEMBER_GROUP_ADMIN"), v.literal("STAFF_DIRECT"), v.literal("GROUP_ANNOUNCEMENT")),
    createdAt: v.number(),
  }).index("by_group_type", ["groupId", "type"]),
  chatParticipants: defineTable({
    conversationId: v.id("chatConversations"),
    userId: v.id("users"),
    joinedAt: v.number(),
    lastReadAt: v.optional(v.number()),
  }).index("by_user", ["userId"]),
  chatMessages: defineTable({
    conversationId: v.id("chatConversations"),
    senderUserId: v.id("users"),
    clientMessageId: v.string(),
    bodyCiphertext: v.string(),
    deliveryStatus: v.union(v.literal("SENT"), v.literal("DELIVERED"), v.literal("READ")),
    createdAt: v.number(),
  }).index("by_conversation_created", ["conversationId", "createdAt"]),
  notifications: defineTable({
    userId: v.id("users"),
    type: v.union(v.literal("SECURITY"), v.literal("LOAN_DUE"), v.literal("LOAN_OVERDUE"), v.literal("FINE"), v.literal("SAVINGS_REMINDER"), v.literal("GROUP_ANNOUNCEMENT"), v.literal("CHAT"), v.literal("SYSTEM")),
    title: v.string(),
    body: v.string(),
    metadata: v.optional(v.string()),
    readAt: v.optional(v.number()),
    createdAt: v.number(),
  }).index("by_user_read", ["userId", "readAt", "createdAt"]),
  securityEvents: defineTable({
    subjectUserId: v.optional(v.id("users")),
    type: v.string(),
    severity: v.union(v.literal("LOW"), v.literal("MEDIUM"), v.literal("HIGH"), v.literal("CRITICAL")),
    status: v.union(v.literal("OPEN"), v.literal("ACKNOWLEDGED"), v.literal("RESOLVED"), v.literal("FALSE_POSITIVE")),
    ipHash: v.optional(v.string()),
    metadata: v.optional(v.string()),
    detectedAt: v.number(),
    resolvedAt: v.optional(v.number()),
  }).index("by_status_severity", ["status", "severity", "detectedAt"]),
  auditEvents: defineTable({
    actorUserId: v.optional(v.id("users")),
    action: v.string(),
    targetType: v.string(),
    targetId: v.optional(v.id("_any")),
    outcome: v.union(v.literal("SUCCESS"), v.literal("FAILURE")),
    requestId: v.optional(v.string()),
    sourceIpHash: v.optional(v.string()),
    beforeJson: v.optional(v.string()),
    afterJson: v.optional(v.string()),
    reason: v.optional(v.string()),
    previousHash: v.optional(v.string()),
    entryHash: v.string(),
    createdAt: v.number(),
  }).index("by_created_at", ["createdAt"]),
  reports: defineTable({
    requestedById: v.id("users"),
    groupId: v.optional(v.id("groups")),
    type: v.string(),
    format: v.string(),
    filters: v.optional(v.string()),
    status: v.union(v.literal("REQUESTED"), v.literal("PROCESSING"), v.literal("READY"), v.literal("FAILED"), v.literal("EXPIRED")),
    fileAssetId: v.optional(v.id("fileAssets")),
    expiresAt: v.optional(v.number()),
    createdAt: v.number(),
    completedAt: v.optional(v.number()),
  }).index("by_requested_status", ["requestedById", "status"]),
});
